In [92]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from typing import List
from pathlib import Path
from typing import Any
from datetime import datetime
from pandas import DataFrame
from pandas import Series

# Config
pd.options.display.float_format = '{:.3f}'.format

# Paths
home_path: str = str(Path.home())
mt5_relative_path: str = "\\AppData\\Roaming\\MetaQuotes\\Terminal\\Common\\Files\\csv_files"
csv_file_path: str = home_path + mt5_relative_path

# File Pattern
csv_file_pattern: str = "BLOCK_REVERSION_*.csv"

# Merge CSVs files
csv_df_list: List[DataFrame] = []
for csv_path in Path(csv_file_path).glob(csv_file_pattern):
    csv_df: DataFrame = pd.read_csv(csv_path, sep = ";")
    csv_df_list.append(csv_df)

# CSV to DataFrame
df_raw: DataFrame = pd.DataFrame()
if len(csv_df_list) > 0 :
    df_raw = pd.concat(csv_df_list, ignore_index=True)
    df_raw.drop_duplicates(inplace=True)

# Aditional Columns
df_raw["mfe_distance_blocks"] = np.where(
        (df_raw["block_size"] > 0), (df_raw["mfe_distance"] / df_raw["block_size"]), 0)

df_raw["mae_distance_blocks"] = np.where(
        (df_raw["block_size"] > 0), (df_raw["mae_distance"] / df_raw["block_size"]), 0)

# Dataset: 2026-01-05 - 2026-05-30
df_raw

,gral_symbol,gral_period,gral_session,gral_setup_time,|,block_pivot_strength,block_type,block_size,|.1,entry_price,...,mae_price,mae_distance,mae_bars,|.3,mfe_price,mfe_distance,mfe_bars,|.4,mfe_distance_blocks,mae_distance_blocks
0,XAUUSD,M15,NEW_YORK,2026.01.02 15:15:00,|,1,BEARISH,47.740,|,4346.108,...,4333.690,12.418,0,|,4347.049,0.941,0,|,0.020,0.260
1,XAUUSD,M15,NEW_YORK,2026.01.02 16:15:00,|,1,BEARISH,32.160,|,4325.906,...,4309.731,16.175,7,|,4396.836,70.930,27,|,2.206,0.503
2,XAUUSD,M15,ALL,2026.01.04 23:15:00,|,1,BEARISH,45.371,|,4362.108,...,4376.010,13.902,0,|,4361.316,0.792,0,|,0.017,0.306
3,XAUUSD,M15,TOKYO,2026.01.05 00:30:00,|,1,BEARISH,42.395,|,4395.103,...,4421.173,26.070,0,|,4394.270,0.833,0,|,0.020,0.615
4,XAUUSD,M15,TOKYO,2026.01.05 01:00:00,|,1,BEARISH,36.099,|,4396.245,...,4406.815,10.570,1,|,4388.713,7.532,2,|,0.209,0.293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25721,XAUUSD,M5,TOKYO,2026.05.29 01:15:00,|,5,BEARISH,28.604,|,4506.355,...,4511.306,4.951,4,|,4494.723,11.632,22,|,0.407,0.173
25722,XAUUSD,M5,TOKYO,2026.05.29 06:55:00,|,5,BEARISH,21.735,|,4511.964,...,4526.279,14.315,4,|,4509.975,1.989,17,|,0.092,0.659
25723,XAUUSD,M5,LONDON,2026.05.29 09:50:00,|,5,BEARISH,29.939,|,4527.001,...,4527.891,0.890,0,|,4525.949,1.052,0,|,0.035,0.030
25724,XAUUSD,M5,LONDON,2026.05.29 10:35:00,|,5,BEARISH,18.086,|,4536.012,...,4538.951,2.939,10,|,4512.672,23.340,20,|,1.291,0.163
25725,XAUUSD,M5,NEW_YORK,2026.05.29 12:45:00,|,5,BEARISH,26.279,|,4522.906,...,4521.307,1.599,0,|,4595.286,72.380,23,|,2.754,0.061

In [ ]:
'''
df_mae = (
    df_raw.groupby(["gral_period", "gral_session"])["mae_distance_blocks"]
    .describe()
    .reset_index()
)

df_mae


# Max. Favorable Excursion
df_mfe = (
    df_raw.groupby(["gral_period", "gral_session"])["mfe_distance_blocks"]
    .describe()
    .reset_index()
)

df_mfe

df_data = df_raw.groupby(
    ["gral_period", "gral_session", "block_pivot_strength"]
)[["mae_distance_blocks", "mfe_distance_blocks"]].agg(
    ["count", "mean", "median", "std"]
)

df_data

-----

# print(df_raw["mae_distance_blocks"].describe(), "\n", df_raw["rr_value"].describe())
data = df_raw["mae_distance_blocks"]

import numpy as np
import matplotlib.pyplot as plt

# Media y desviación estándar
mu = np.mean(data)
sigma = np.std(data)

# Histograma
plt.hist(data, bins=40, density=True, alpha=0.6)

# Función de densidad normal
x = np.linspace(min(data), max(data), 500)
y = (1 / (sigma * np.sqrt(2 * np.pi))) * np.exp(-0.5 * ((x - mu) / sigma) ** 2)

plt.plot(x, y, linewidth=2)

plt.show()

df_raw["mae_distance_blocks"].hist(bins=5)

plt.xlabel("MAE (blocks)")
plt.ylabel("Frequency")
plt.title("Distribution of MAE")
plt.show()

import matplotlib.pyplot as plt
import scipy.stats as stats

stats.probplot(
    df_raw["mae_distance_blocks"],
    dist="norm",
    plot=plt
)

plt.title("Q-Q Plot - MAE")
plt.show()


'''

print("MAE MFE by Period + Pivot Strength")
df_mae = df_raw.groupby(["gral_period", "block_pivot_strength"])[["mae_distance_blocks", "mfe_distance_blocks"]].describe()
df_mae

MAE MFE by Period + Pivot Strength

                                 mae_distance_blocks                          \
                                               count  mean   std   min   25%
gral_period block_pivot_strength
M1          1                               6958.000 0.251 0.241 0.000 0.083
            2                               4748.000 0.231 0.221 0.000 0.077
            3                               3647.000 0.213 0.204 0.000 0.069
            4                               2949.000 0.204 0.206 0.000 0.065
            5                               2491.000 0.202 0.200 0.000 0.064
M15         1                                397.000 0.253 0.240 0.000 0.082
            2                                258.000 0.206 0.190 0.000 0.066
            3                                213.000 0.200 0.201 0.000 0.067
            4                                191.000 0.186 0.172 0.005 0.054
            5                                165.000 0.185 0.186 0.000 0.056
M5          1                               1225.000 0.261 0.235 0.000 0.094
            2                                821.000 0.234 0.220 0.000 0.079
            3                                667.000 0.221 0.205 0.000 0.077
            4                                540.000 0.205 0.196 0.000 0.071
            5                                456.000 0.197 0.206 0.000 0.064

                                                   mfe_distance_blocks        \
                                   50%   75%   max               count  mean
gral_period block_pivot_strength
M1          1                    0.190 0.344 2.674            6958.000 0.872
            2                    0.175 0.316 3.069            4748.000 0.822
            3                    0.156 0.296 1.752            3647.000 0.802
            4                    0.147 0.279 1.910            2949.000 0.827
            5                    0.142 0.277 1.849            2491.000 0.820
M15         1                    0.182 0.363 1.518             397.000 0.851
            2                    0.150 0.282 1.090             258.000 0.822
            3                    0.129 0.283 1.363             213.000 0.813
            4                    0.137 0.264 0.995             191.000 0.768
            5                    0.134 0.250 1.237             165.000 0.805
M5          1                    0.200 0.354 1.674            1225.000 0.865
            2                    0.180 0.313 2.155             821.000 0.864
            3                    0.164 0.292 1.326             667.000 0.812
            4                    0.151 0.282 1.611             540.000 0.826
            5                    0.140 0.272 1.867             456.000 0.798


                                   std   min   25%   50%   75%    max
gral_period block_pivot_strength
M1          1                    1.005 0.000 0.198 0.578 1.267 23.009
            2                    0.955 0.000 0.190 0.545 1.190 22.933
            3                    0.948 0.000 0.182 0.523 1.144 20.057
            4                    1.125 0.000 0.178 0.518 1.166 22.024
            5                    1.108 0.000 0.167 0.504 1.120 20.260
M15         1                    0.983 0.008 0.210 0.512 1.201  6.969
            2                    0.941 0.001 0.186 0.533 1.142  6.121
            3                    0.990 0.001 0.160 0.411 1.113  5.891
            4                    0.923 0.003 0.157 0.412 1.073  5.766
            5                    1.076 0.000 0.191 0.422 1.159  9.114
M5          1                    0.948 0.000 0.191 0.544 1.198  6.065
            2                    1.022 0.000 0.191 0.530 1.167  8.853
            3                    0.960 0.000 0.183 0.495 1.100  7.186
            4                    1.046 0.000 0.171 0.485 1.141  8.116
            5                    0.941 0.002 0.172 0.485 1.111  6.399